Chromino/Controllers/GamesController.cs
using Controllers;
using Data;
using Data.DAL;
using Data.Models;
using Data.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace ChrominoApp.Controllers
{
    [Authorize]
    public class GamesController : CommonController
    {
        public GamesController(Context context, UserManager<Player> userManager, IWebHostEnvironment env) : base(context, userManager, env)
        {
        }

        /// <summary>
        /// Page d'accueil des parties
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Page des parties entre amis
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = nameof(Player))]
        public IActionResult AgainstFriends()
        {
            return View(MakePicturesGameVM(GamePlayerDal.MultiGamesAgainstAtLeast1HumanToPlay(PlayerId), true));
        }

        public IActionResult AgainstFriendsAjax()
        {
            var picturesGame = MakePicturesGameVM(GamePlayerDal.MultiGamesAgainstAtLeast1HumanToPlay(PlayerId), true);
            return new JsonResult(new { picturesGame });
        }

        /// <summary>
        /// Page des parties à jouer contre uniquement des bots 
        /// </summary>
        /// <returns></returns>
        public IActionResult AgainstBots()
        {
            return View(MakePicturesGameVM(GamePlayerDal.GamesAgainstBotsOnly(PlayerId), true));
        }

        /// <summary>
        /// Page des parties d'entrainement en cours
        /// </summary>
        /// <returns></returns>
        public IActionResult SingleGame()
        {
            List<PictureGameVM> picturesGameVM = MakePicturesGameVM(GamePlayerDal.SingleGamesInProgress(PlayerId));
            if (picturesGameVM.Count == 0)
                return RedirectToAction("NewSingle", "Game");
            else
                return View(picturesGameVM);
        }

        /// <summary>
        /// Page des parties en cours (tour d'un adversaire)
        /// </summary>
        /// <returns></returns>
        public IActionResult InProgress()
        {
            return View(MakePicturesGameVM(GamePlayerDal.GamesWaitTurn(PlayerId), true));
        }

        /// <summary>
        /// Page des parties solo terminées
        /// </summary>
        /// <returns></returns>
        public IActionResult SingleFinished()
        {
            return View(MakePicturesGameVM(GamePlayerDal.SingleGamesFinished(PlayerId)));
        }

        [HttpGet]
        public IActionResult Guids(int gameId)
        {
            var guids = GameDal.ListGuids(PlayerId);
            return new JsonResult(new { guids });
        }
    }
}

Chromino/Controllers/StatisticsController.cs
using Controllers;
using Data;
using Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ChrominoApp.Controllers
{
    [Authorize(Roles = nameof(Player))]
    public class StatisticsController : CommonController
    {
        public StatisticsController(Context context, UserManager<Player> userManager, IWebHostEnvironment env) : base(context, userManager, env)
        {
        }

        public IActionResult Index(int gameId)
        {
            return View();
        }

        public IActionResult Won(int gameId)
        {
            return View(MakePicturesGameVM(GamePlayerDal.GamesWon(PlayerId)));
        }

        public IActionResult Lost(int gameId)
        {
            return View(MakePicturesGameVM(GamePlayerDal.GamesLost(PlayerId)));
        }
    }
}

Chromino/Views/Statistics/Index.cshtml
@{
    ViewData["Title"] = "Statistiques";
}

<p><a asp-area="" asp-controller="Games" asp-action="Index">Retour</a></p>

<div class="icones-link">
    <a class="icone-link" asp-action="Won">
        <div class="btn btn-homepage img-won"></div>
        <div>Parties gagnées</div>
    </a>
    <a class="icone-link" asp-action="Lost">
        <div class="btn btn-homepage img-lost"></div>
        <div>Parties perdues</div>
    </a>
</div>

Chromino/Views/Statistics/Lost.cshtml
@using  Data.ViewModel
@model List<PictureGameVM>
@{
    ViewData["Title"] = "Games lost";
    int gamesNumber = Model.Count;
}
<p><a asp-controller="Statistics" asp-action="Index">Retour</a></p>

@switch (gamesNumber)
{
    case 0:
        <p><b>Vous n'avez aucune partie perdues</b></p>
        break;
    case 1:
        <h3>Vous avez 1 partie perdue</h3>
        <partial name="_ThumbnailPartial" model="Model" />
        break;
    default:
        <h3>Vous avez @gamesNumber parties perdues</h3>
        <partial name="_ThumbnailPartial" model="Model" />
        break;
}
<br />
<p><a asp-area="" asp-controller="Games" asp-action="Index">Retour</a></p>

Chromino/Views/Statistics/Won.cshtml
@using  Data.ViewModel
@model List<PictureGameVM>
@{
    ViewData["Title"] = "Games won";
    int gamesNumber = Model.Count;
}
<p><a asp-controller="Statistics" asp-action="Index">Retour</a></p>

@switch (gamesNumber)
{
    case 0:
        <p><b>Vous n'avez aucune partie gagnée</b></p>
        break;
    case 1:
        <h3>Vous avez 1 partie gagnée</h3>
        <partial name="_ThumbnailPartial" model="Model" />
        break;
    default:
        <h3>Vous avez @gamesNumber parties gagnées</h3>
        <partial name="_ThumbnailPartial" model="Model" />
        break;
}
<br />
<p><a asp-area="" asp-controller="Games" asp-action="Index">Retour</a></p>